onboarding = false

[theme]
name = "catppuccin"
auto_switch = true
light_name = "catppuccin-latte"
dark_name = "catppuccin-mocha"

[keys]
prefix = "ctrl+'"
navigate_workspace_up = "k"
navigate_workspace_down = "j"
